### ISSUE TITLE
File based caching causes attempt to sync which throws an error

### ISSUE THREAD

**Issue by lucasjans** [maxiomtech/DotNetNuke-FileWatcher#1]
The file based caching causes the watcher to trigger, which throws this error.

```
DotNetNuke.Services.FileSystem.InvalidFileExtensionException: The extension '.resources' is not allowed. The file has not been added.
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, String contentType, Int32 createdByUserID)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, String contentType)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite)
   at InspectorIT.FileWatcher.Components.FileMonitor.onFileChanged(Object sender, FileSystemEventArgs e, PortalInfo portalInfo)
```

I will put in a pull request to fix it. Should we not throw an error for file types that are excluded? Maybe a warning? Or perhaps certain types of files should be ignored?

**Comment by jsheely** [comment]
Yes, That's a good idea. Only the files types in the include Host Settings include list should added.
